In [2]:
%pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:

import pandas as pd

In [5]:
data = pd.read_csv("../data/project_1_ANSC_4040_dataset.csv")

data.head()

/var/folders/3m/18rctxnj5ls7nv2_3_17zjfc0000gn/T/ipykernel_75886/2719582108.py:1: DtypeWarning: Columns (0: ReproductionStatus) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../data/project_1_ANSC_4040_dataset.csv")

,AnimalNumber,LactationNumber,DaysInMilk,ReproductionStatus,Avgmilkflow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_sec,milking
0,31317.0,2.0,255.0,Pregnant,2.812273,2.898455,5.874021,8.028585,168,2
1,60614.0,1.0,251.0,Pregnant,2.902991,3.801104,6.372973,7.030682,143,1
2,36947.0,1.0,183.0,Pregnant,3.401943,3.701314,7.048825,16.374685,285,3
3,31720.0,2.0,82.0,Bred,4.309128,4.799007,8.876803,18.461209,256,1
4,23630.0,6.0,182.0,Pregnant,3.719457,3.701314,7.874364,13.199538,210,3

In [6]:
# Check the dimensions of the dataset
print("Number of rows:", data.shape[0])
print("Number of columns:", data.shape[1])

# Display column names
print("\nColumn names:")
print(data.columns.tolist())

Number of rows: 8495421
Number of columns: 10

Column names:
['AnimalNumber', 'LactationNumber', 'DaysInMilk', 'ReproductionStatus', 'Avgmilkflow', 'Flow30_60Session', 'YieldFirst2Min_Session', 'YieldSession', 'DurationSession_sec', 'milking']

In [7]:
# Check data types
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8495421 entries, 0 to 8495420
Data columns (total 10 columns):
 #   Column                  Dtype
---  ------                  -----
 0   AnimalNumber            float64
 1   LactationNumber         float64
 2   DaysInMilk              float64
 3   ReproductionStatus      str
 4   Avgmilkflow             float64
 5   Flow30_60Session        float64
 6   YieldFirst2Min_Session  float64
 7   YieldSession            float64
 8   DurationSession_sec     int64
 9   milking                 int64
dtypes: float64(7), int64(2), str(1)
memory usage: 648.1 MB

In [8]:
# Check missing values
missing_values = data.isnull().sum()

print("Missing values by column:")
print(missing_values)

Missing values by column:
AnimalNumber              1701003
LactationNumber           1701003
DaysInMilk                1701007
ReproductionStatus        1701003
Avgmilkflow                   172
Flow30_60Session                0
YieldFirst2Min_Session          0
YieldSession                    0
DurationSession_sec             0
milking                         0
dtype: int64

In [9]:
# Summary statistics for numerical variables
data.describe()

,AnimalNumber,LactationNumber,DaysInMilk,Avgmilkflow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_sec,milking
count,6.794418e+06,6.794418e+06,6.794414e+06,8.495249e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06
mean,3.243931e+04,2.293987e+00,1.629297e+02,3.525963e+00,3.751556e+00,7.491106e+00,1.392847e+01,2.368638e+02,2.000000e+00
std,5.079711e+03,1.387657e+00,1.055188e+02,7.291427e-01,1.485679e+00,2.014112e+00,3.645984e+00,5.484328e+01,8.164966e-01
min,1.103800e+04,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,2.000342e+00,5.034875e+00,1.000000e+02,1.000000e+00
25%,2.978200e+04,1.000000e+00,7.600000e+01,2.993710e+00,2.798665e+00,6.023707e+00,1.143053e+01,1.970000e+02,1.000000e+00
50%,3.274300e+04,2.000000e+00,1.540000e+02,3.492661e+00,3.900894e+00,7.525097e+00,1.374385e+01,2.310000e+02,2.000000e+00
75%,3.484700e+04,3.000000e+00,2.370000e+02,3.991613e+00,4.898798e+00,8.999273e+00,1.632933e+01,2.720000e+02,3.000000e+00
max,6.063000e+04,1.200000e+01,8.700000e+02,2.349608e+01,1.050066e+01,1.199752e+01,5.483932e+01,7.850000e+02,3.000000e+00

In [10]:
# Check categorical variables
print("Reproduction Status:")
print(data["ReproductionStatus"].value_counts(dropna=False))

print("\nMilking:")
print(data["milking"].value_counts(dropna=False).sort_index())

Reproduction Status:
ReproductionStatus
Pregnant    3357267
Bred        1844972
NaN         1701003
Fresh        969753
Open         622426
Name: count, dtype: int64

Milking:
milking
1    2831807
2    2831807
3    2831807
Name: count, dtype: int64

In [11]:
# Check duplicate rows
duplicate_rows = data.duplicated().sum()

print("Number of duplicate rows:", duplicate_rows)

Number of duplicate rows: 78586