In [16]:
%pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [17]:

import pandas as pd

In [25]:
data = pd.read_csv("../data/Data_set_new.csv")

data.head()

,AnimalId,LactationNumber,DaysInMilk,ReproductionStatus,EventDate,Avgmilkflow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_sec,milking
0,-8.839529e+18,1.0,365.0,Pregnant,2019-12-09,2.902991,0.898113,4.975908,11.158372,226,1
1,-5.365332e+18,1.0,66.0,Bred,2021-07-12,3.311224,1.401600,5.347854,15.059267,268,2
2,NaN,NaN,NaN,NaN,2020-08-24,3.220506,3.501733,7.547777,14.560315,270,1
3,7.750424e+18,1.0,244.0,Pregnant,2019-12-04,3.900894,4.100475,8.400531,15.331422,231,3
4,NaN,NaN,NaN,NaN,2021-03-21,4.218409,5.098378,9.198853,13.970645,198,2

In [28]:
# Check the dimensions of the dataset
print("Number of rows:", data.shape[0])
print("Number of columns:", data.shape[1])

# Display column names
print("\nColumn names:")
print(data.columns.tolist())

Number of rows: 8495421
Number of columns: 11

Column names:
['AnimalId', 'LactationNumber', 'DaysInMilk', 'ReproductionStatus', 'EventDate', 'Avgmilkflow', 'Flow30_60Session', 'YieldFirst2Min_Session', 'YieldSession', 'DurationSession_sec', 'milking']

In [20]:
# Check data types
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 8495421 entries, 0 to 8495420
Data columns (total 11 columns):
 #   Column                  Dtype
---  ------                  -----
 0   AnimalId                float64
 1   LactationNumber         float64
 2   DaysInMilk              float64
 3   ReproductionStatus      str
 4   EventDate               str
 5   Avgmilkflow             float64
 6   Flow30_60Session        float64
 7   YieldFirst2Min_Session  float64
 8   YieldSession            float64
 9   DurationSession_sec     int64
 10  milking                 int64
dtypes: float64(7), int64(2), str(2)
memory usage: 713.0 MB

In [33]:
# Check missing values
missing_values = data.isnull().sum()

print("Missing values by column:")
print(missing_values)

Missing values by column:
AnimalId                  1701003
LactationNumber           1701003
DaysInMilk                1701007
ReproductionStatus        1701003
EventDate                       0
Avgmilkflow                   172
Flow30_60Session                0
YieldFirst2Min_Session          0
YieldSession                    0
DurationSession_sec             0
milking                         0
dtype: int64

In [32]:
# Summary statistics for numerical variables
data.describe()

,AnimalId,LactationNumber,DaysInMilk,Avgmilkflow,Flow30_60Session,YieldFirst2Min_Session,YieldSession,DurationSession_sec,milking
count,6.794418e+06,6.794418e+06,6.794414e+06,8.495249e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06,8.495421e+06
mean,1.696873e+16,2.293987e+00,1.629297e+02,3.525963e+00,3.751556e+00,7.491106e+00,1.392847e+01,2.368638e+02,2.000000e+00
std,5.313047e+18,1.387657e+00,1.055188e+02,7.291427e-01,1.485679e+00,2.014112e+00,3.645984e+00,5.484328e+01,8.164966e-01
min,-9.221543e+18,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,2.000342e+00,5.034875e+00,1.000000e+02,1.000000e+00
25%,-4.602933e+18,1.000000e+00,7.600000e+01,2.993710e+00,2.798665e+00,6.023707e+00,1.143053e+01,1.970000e+02,1.000000e+00
50%,4.495373e+16,2.000000e+00,1.540000e+02,3.492661e+00,3.900894e+00,7.525097e+00,1.374385e+01,2.310000e+02,2.000000e+00
75%,4.597954e+18,3.000000e+00,2.370000e+02,3.991613e+00,4.898798e+00,8.999273e+00,1.632933e+01,2.720000e+02,3.000000e+00
max,9.218000e+18,1.200000e+01,8.700000e+02,2.349608e+01,1.050066e+01,1.199752e+01,5.483932e+01,7.850000e+02,3.000000e+00

In [31]:
print(data["EventDate"].head())
print(data["EventDate"].dtype)

0    2019-12-09
1    2021-07-12
2    2020-08-24
3    2019-12-04
4    2021-03-21
Name: EventDate, dtype: str
str